library(ggplot2)
library(gridExtra)
library(dplyr)
library(leaflet)
library(corrplot)
library(leaflet)
library(readxl)
library(mblm)
source('./00manipulando_dados.R')
#SO TRISTEZA 
# fit0<-lm(n_potes_mel~comp_canudo,data)
# fit1<-mblm(n_potes_mel~comp_canudo,data)
# summary(fit1)
# par(mfrow = c(1,1), mar = c(4, 5, 2, 1), pch = 19)
# plot(data$n_potes_mel~data$comp_canudo, pch = 19)
# abline(fit1, lty = 1, lwd = 2, col = "red")
# text(4.5,4, "Modelo Theil-Kendall", col = "red")
# abline(fit0, lty = 1, lwd = 2, col = "blue")
# text(4,8, "Modelo de regressão linear", col = "blue")
