library(ggplot2)
library(gridExtra)
library(dplyr)
library(leaflet)
library(corrplot)
library(leaflet)
library(readxl)
library(car)
library(PMCMR)

data <- read.table('./data/data.csv', sep=',', h=T)
